services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - "8000:8000"
    depends_on:
      - database
    tty: true

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SomePassword"
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"