IF NOT EXISTS (SELECT NAME FROM SYS.DATABASES WHERE NAME='$(DATABASE_NAME)')
BEGIN
    CREATE DATABASE $(DATABASE_NAME)
END;
GO

USE $(DATABASE_NAME);
GO

IF NOT EXISTS (SELECT NAME FROM SYS.TABLES WHERE NAME='ShoppingList')
BEGIN
    CREATE TABLE ShoppingList (datestamp NCHAR(10), buyer NVARCHAR(50), apples INT, oranges INT, id INT)
END;
GO