name: Ruff
on: [ pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Linting with Ruff"
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          args: --fix
